#################################################
# Hammerflow config for MacBook Pro
#################################################

# settings
leader_key = "f18"        # required, the leader key that starts the sequence
leader_key_mods = ""      # optional, default "", not recommended - a dedicated leader key is better
                          # supports cmd ctrl alt shift
auto_reload = true        # optional, default true, reload when any file in this directory is saved
toast_on_reload = true    # optional, default false, show a toast when the config is reloaded
show_ui = true            # optional, default true, show the ui with your key maps

# set a key to open an app

h = "Heptabase"
o = "OrbStack"
t = "TablePlus"
v = ["Visual Studio Code", "VS Code"]
w = "Windsurf"

[b]
label = "[b]"
b = "Brave Browser"
r = "Bruno"

[c]
label = "[c]"
a = "Cap"
h = ["Google Chrome", "Chrome"]

[g]
label = "[g]"
h = "Ghostty"

[s]
label = "[s]"
p = "Spark"
b = "SnippetsLab"

# this group is handy to copy over
# for quick access to your config
[q]
label = "[hammerspoon]"
c = "code: ~/.hammerspoon"
r = "reload" # reserved for reloading your hammerspoon config (helpful when auto_reload is false)
